site_name: SSE Documentation Example
nav:
    - Home: 'index.md'
    - 'User guide':
        - Installation: 'compilation-and-installation.md'
        - Getting Started: 'how-to.md'
repo_url: https://github.com/mohamad-altaweel/sse-mkdocs-exercise
site_author: mohamad-altaweel